backend:
  name: git-gateway
  branch: main
media_folder: "public/img"
public_folder: "/img"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogholder"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string"}      
      - { label: "Description", name: "description", widget: "string"}      
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Date", name: "date", widget: "datetime"}    
      - { label: "Time", name: "time", widget: "string"}    
      - { label: "Tags", name: "tags", widget: "list", default: ["post"]}    
      - { label: "Layout", name: "layout", widget: "string", default: 'article.njk'}    
      - { label: "Featured Image", name: "image", widget: "image"}
      - { label: "Alt text", name: "alt", widget: "string"}
      - { label: "Keywords", name: "keywords", widget: "string"}
      - { label: "Page Description", name: "pageDescription", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}    

